### PR TITLE
simple fix to #713

### PR DESCRIPTION
**Pull request by pgkirsch**

### CODE REVIEW

**Comment by bqpd** [comment]
Annoying that this triggers pylint errors...

**Comment by galbramc** [comment]
The pylint warnings seem legitimate though:

```
sensitivity_map.py:35, PyLint, Priority: Normal
Access to a protected member _latex of a client class

sensitivity_map.py:106, PyLint, Priority: Normal
Access to a protected member _latex of a client class
```
Looks like you are calling a protected member outside of the class. If you intend to have latex() called from outside the class, it should not have an underscore in the name. At least that's my understanding.

**Comment by bqpd** [comment]
Oh, the calls are legit, but they're not in the single line of code this PR alters, and fixing them entails much more work / design discussion than the actual fix that motivated this PR.

**Comment by galbramc** [comment]
Was there a pull request that has not been merged yet that fixed these warnings? I think that's the only way why these warnings would not be ignored right now. Any successful pull request effectively resets the counts.

**Comment by bqpd** [comment]
Oh! Yeah, it looks like #708 fixed them but hasn't been merged yet. Will merging this not actually cause pylint errors, then?

**Comment by galbramc** [comment]
Yeah, so if you merge this it will not cause any errors on gpkit_push.

We can reset the counts, or you can merge #708 to fix the fact that you get these pylint warnings on all pull requests at the moment. This is why it is problematic to have unfixed pylint warnings.

**Pull request merged**
