### PR TITLE
don't re-bring costvals into sp substitutions

### LINKED ISSUE #1131: substitutions not deleting
@bqpd @whoburg ahh! need you're help on this quick! 

Running `gasmaleperf.py` on jho repo on branch `newsolves`.  It appear that deleting a substitution only temporarily deletes it re-inserts it when trying to solve.  I'm convinced this is why I got `DUAL_INFEAS` because I know it will solve with higher payloads.  Below is the ipython output (I also saw the same behavior as a script):

```python 
In [1]: %run gasmaleperf.py
Beginning signomial solve.
Allowing negative dual variable(s) as small as -1.69108000173e-12.
Allowing negative dual variable(s) as small as -1.64037945553e-13.
Solving took 4 GP solves and 24.2 seconds.
144.324433952

In [2]: M.cost = 1./M["W_{pay}"]

In [3]: del M.substitutions["W_{pay}"]

In [4]: M.substitutions["W_{pay}"]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...
KeyError: W_{pay}_Mission/Aircraft

In [5]: sol = M.localsolve("mosek")
Beginning signomial solve.
RuntimeWarning: final status of solver 'mosek' was 'DUAL_INFEAS_CER', not 'optimal'.

The solver's result is stored in model.program.solver_out. A result dict can be generated via program._compile_result(program.solver_out).

In [6]: M.substitutions["W_{pay}"]
Out[6]: 10
```

### PR DESCRIPTION
**Pull request by bqpd**
@whoburg. @mjburton11 , fixes #1131. Ready for review.

### CODE REVIEW

**Comment by mjburton11** [comment]
@whoburg, @bqpd I'm really close to getting the JHO metrics to print out, but it I need to use the `del` function more than once and will be fairly difficult without this PR.  Any chance it could be done tonight?

**Comment by mjburton11** [comment]
Is it failing gpkit-model test, just because there aren't any tests?

**Comment by mjburton11** [comment]
Also, was I given access to approve changes? Cause that would be dope if I was...

**Comment by bqpd** [comment]
@mjburton11, merging for your sake; @whoburg, feel free to revert if you disagree!

**Comment by bqpd** [comment]
test models please

**Comment by mjburton11** [comment]
Can I approve the review?

**Comment by mjburton11** [comment]
nevermind haha

**Comment by whoburg** [comment]
@bqpd @mjburton11 forgot to tag you in review above re: unit test

**Comment by bqpd** [comment]
Any replacement of the cost with a variable that has a value should do!

**Pull request merged**
