### PR TITLE
suitesparse -> libsuitesparse, typo fixes

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test gpkit please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
So you are replacing ipywidgets with jupyer? Should I do the same in all the tests scripts so they match your install instructions?

**Comment by galbramc** [comment]
test models please

**Comment by bqpd** [comment]
Jupyter now installs ipywidgets!

**Comment by galbramc** [comment]
Ok, you should fix the typo of 'pip install jupyer' to 'pip install jupyter'

So if the install instructions now suggest using jupyter, we should update all the testing scripts to install that instead of just installing ipywidgets. Correct?

**Comment by bqpd** [comment]
We don't currently test anything with ipywidgets, though, right? And it's the thing we acually import.

**Comment by bqpd** [comment]
Installing jupyter can take some time (if you don't have libzmq installed it compiles it), so maybe we could do that just for gpkit_Install?

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@whoburg, ready for review (it's just docs fixes, so I'll merge it now to avoid confusing anyone with bad installation instructions...)

**Pull request merged**
