### PR TITLE
remove old docstring info, unneeded pylint suppression

### PR DESCRIPTION
**Pull request by whoburg**
minor cleanups...

ready for review.

### CODE REVIEW

**Comment by bqpd** [comment]
Looks good to me.

**Comment by whoburg** [comment]
@galbramc, it looks like this is failing due to recently added git status check

**Comment by galbramc** [comment]
Indeed it is. So do you consider this a real or fake error. From what you told me earlier this means there is some sort of error with the examples. I have not added the test to gpki_Push, but the error is in the master branch so all PRs will fail with this test.

**Comment by galbramc** [comment]
What order are the solvers tested? I'm guessing it's either the mosek interface or mosek_ci. That is falling. I added the check to depends as well, but it looks like the last solver is overwriting the incorrect results with correct ones.

**Comment by whoburg** [comment]
Oh, yeah, that's the problem -- we generate the examples output with a specific solver (cvxopt). So the git status check should happen on the cvxopt machines only.

the ouput can be different for mosek due to numerical precision.

**Comment by galbramc** [comment]
test this please

Only the cvxopt solver now checks for modified files

**Comment by galbramc** [comment]
Sines this is a cleanup PR, maybe the handful of pylint warnings in the gpkit/test folder could be fixed? Suppress or move import statement warnings?

**Comment by galbramc** [comment]
Nice. Fixed another 10 warnings!

Of course, pylint will fail for all other PRs until this is merged...

**Comment by whoburg** [comment]
haha. ok - @bqpd was happy, so merging.

**Pull request merged**
