### PR TITLE
use slash for indicating submodels

### PR DESCRIPTION
**Pull request by bqpd**
@mayork, @mjburton11, @1ozturkbe, what do you think about using slashes to delimit submodels?

@whoburg, ready for review.

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mayork, @mjburton11, what do you think of this?

**Comment by bqpd** [comment]
test models please

**Comment by whoburg** [comment]
would also be fine with backslash, or pipe -- anything but the standard list separator in python.

**Comment by bqpd** [comment]
It breaks some of the models, is my main hesitation. Might have to wait until I can merge it / update everyone's models the same day...

**Comment by whoburg** [comment]
please test models

**Comment by whoburg** [comment]
test models please

**Comment by bqpd** [comment]
(it might be only jho / gas_solar that it breaks, I forget)

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mjburton11, are you still using the current commaspace modelname convention to access variables/solutions? This PR will break that...

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Pull request merged**
