### PR TITLE
update unit definitions to pint 0.7.2

### PR DESCRIPTION
**Pull request by whoburg**
This should make it easier to update unit definitions in track with pint.

The 0.6 --> 0.7.2 update includes `"gal"` as requested in #661.

Ready for review.

### CODE REVIEW

**Comment by whoburg** [comment]
Hmm, even though this passes the unit tests on pint 0.6 and 0.7.2, if one has pint 0.6 installed and opens an ipython notebook and executes `import gpkit`, then a bunch of errors/warnings occur (only reproducable in ipython notebook).

I'm guessing that the issue is that pint 0.6 does not know how to process parts of the new `default_en.txt`.

**Comment by whoburg** [comment]
until https://github.com/hgrecco/pint/issues/361 is resolved, it's probably easiest to derive the unit definitions directly from the user's pint installation, and then tack on our extras. I added a commit that does that.

Ready for review.

**Comment by galbramc** [comment]
Should I add ipython in the unit testing scripts so something like this does not slip by?

**Comment by whoburg** [comment]
it doesn't occur in ipython, only in an ipython notebook...

**Comment by galbramc** [comment]
So is this what we should use: https://pypi.python.org/pypi/pytest-ipynb

**Comment by whoburg** [comment]
brilliant, I'll add a new issue for using that to test various things

**Comment by galbramc** [comment]
Let me know what you need me to do

**Pull request merged**
