### PR TITLE
individual process_solutions for sweeps

### LINKED ISSUE #913: Sweeps pass a vectorized solution to process_solution
@bqpd, I'm getting this error when trying to run sweeps:

``` python
/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpkit/nomials/substitution.pyc in substitution(nomial, substitutions)
    146                 #                          " '%s' into '%s' of units '%s'." %
    147                 #                          (sub, var, var.units.units))
--> 148                 if sub != 0:
    149                     mag(cs_)[i] *= sub**x
    150                 elif x > 0:  # HACK to prevent RuntimeWarnings

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### PR DESCRIPTION
**Pull request by bqpd**
closes #913, #911

### CODE REVIEW

**Comment by mjburton11** [comment]
I've been working on `feasmodtest` but when I tried running my model on `sweepproc`, ran into this error: 

```python
/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/substitution.pyc in substitution(nomial, substitutions)
    128             if getattr(sub, "shape", False):
    129                 raise ValueError("cannot substitute array %s for variable %s"
--> 130                                  % (sub, var))
    131             if isinstance(sub, Numbers):
    132                 if hasattr(sub, "units") and hasattr(sub, "to"):

ValueError: cannot substitute array \bar{S}_Beam_(0,) for variable \bar{S}_(0,)
```

**Comment by bqpd** [comment]
Okay, I'll upload a new branch which is feasmodtest + these changes

**Comment by mjburton11** [comment]
Ok

**Comment by bqpd** [comment]
Try `feassweep`

**Comment by mjburton11** [comment]
hm got the same error

**Comment by bqpd** [comment]
Oh lol I know what's up.

**Comment by bqpd** [comment]
Try now.

**Comment by mjburton11** [comment]
Yep this worked!

**Comment by bqpd** [comment]
:+1: both?

**Comment by mjburton11** [comment]
Yes both!

**Comment by bqpd** [comment]
@whoburg, ready for review

**Comment by mjburton11** [comment]
Wait hold on: I just got this error while trying to run.  

```python 
 File "/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/constraints/set.py", line 287, in process_solution
    constraint.process_solution(sol)
  File "/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/constraints/tight.py", line 24, in process_solution
    leftsubbed = constraint.left.sub(variables).value
  File "/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/nomial_math.py", line 215, in sub
    _, exps, cs, _ = substitution(self, substitutions)
  File "/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/substitution.py", line 111, in substitution
    subs, _, _ = parse_subs(nomial.varkeys, substitutions)
  File "/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/substitution.py", line 22, in parse_subs
    append_sub(sub, keys, constants, sweep, linkedsweep)
  File "/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/substitution.py", line 63, in append_sub
    key.shape))
ValueError: cannot substitute array of shape (15, 1) for variable z_{bre}_BreguetEndurance, TakeOff, Mission, GasMALE_(0,) of shape (1,).
make: *** [all] Error 1
```

**Comment by mjburton11** [comment]
I'm also post processing some other things that I don't need calculated when I do a sweep.  I don't know if it's a good idea to have a boolean value that does the post processing for a sweep if True.

**Comment by whoburg** [comment]
@bqpd, this has a) a merge conflict, b) failing pylint, and c) @mjburton11's latest comment. Have not yet begun review. Let me know when I should review.

**Comment by bqpd** [comment]
This PR does not do what it says it does...working on a new one.

**Pull request closed without merging**
