### PR TITLE
simplify unitstr

### PR DESCRIPTION
**Pull request by whoburg**
minor simplifications. passes all tests, so if these changes are unacceptable let's add test(s) to catch the issue(s).

### CODE REVIEW

**Comment by whoburg** [comment]
ready for review.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
So this breaks pint 0.6. Do you still want to support pint 0.6?

**Comment by bqpd** [comment]
@whoburg

**Comment by whoburg** [comment]
Ok, the pint 0.6 issue was that pint changed the way `Unit` objects are formatted from 0.6 to 0.7.2. The following illustrates the issue (independent of `unitstr`):

```python
from gpkit import units
print "{:~}".format(units("foot").units)
print "{:~}".format(units("nautical_mile").units)
```
On pint 0.6, the output is
```
foot
nautical_mile
```
On pint 0.7.2, the output is 
```
ft
nmi
```
Because of this, I think it's ok for our users to have different unit formatting depending on which version of pint they have installed. I updated the unit test accordingly.

Ready for re-review.

**Pull request merged**
