### PR TITLE
remove wrong docs

### LINKED ISSUE #939: test that different SP formulations solve faster
Since the docs say:

The specification of a signomial problem can affect its solve time in a nuanced way: ``gpkit.Model(x, [x >= 0.1, x+y >= 1, y <= 0.1]).localsolve()`` takes about twice as long to solve with cvxopt as ``gpkit.Model(x, [x >= 1-y, y <= 0.1]).localsolve()``, despite the two formulations being arithmetically equivalent and taking the same number of iterations.

### PR DESCRIPTION
**Pull request by bqpd**
Closes #939

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@whoburg, I'm just going to go ahead and merge this small docs change...

**Comment by whoburg** [comment]
I'm back online, would appreciate a little time to finish reviewing open stuff. Will be responsive.

**Comment by bqpd** [comment]
Yup!

**Pull request merged**
