### PR TITLE
Fast SP

### PR DESCRIPTION
**Pull request by bqpd**
@mayork, @1ozturkbe, this implements an experimental A-matrix-changing faster SP alg; see if it works on your code! This is based on 4cce21bc7e42f816d65f62164162cc681f066321, which you said worked? (don't update it to the current master!)

Known strangenesses:
  - sp.gps no longer gives you access to every gp
  - SP boundedness no longer checks for "sensitive to boundary", just "near to"

@edfan, here's one implementation of the hacky way to do this I proposed on another thread.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
Omg much excitement! Can't wait to put to the test!

**Comment by bqpd** [comment]
retest this please (it passes tests on all solvers here)

**Comment by bqpd** [comment]
@galbramc, it's not clear why this is failing on cvxopt on linux/mac? No test failures, no failures in parsed console output...

**Comment by bqpd** [comment]
Ah, found it, for some reason the parsed console output on reynolds wasn't showing it, but macys does; forgot to commit the relaxation output changes.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@1ozturkbe, @mayork, this brings `SP_aircraft.__main__` at 53a872894d1e822eeb40ac27196c5e24c135646e from ~60s to 20s on my machine, identical solutions.

Note that with the current fast sp there isn't a `.gps` attribute, but instead a `.results` attribute, so `post_process` needs to be modified to the below:

```python
def post_process(sol):
    """
    Model to print relevant info for a solved model with relaxed constants

    ARGUMENTS
    --------
    sol: the solution to the solved model
    """

    for i in range(len(sol.program.gps)):
        varkeys = [k for k in sol.program.gps[i].varlocs
                   if "Relax" in k.models
                   and sol.program.results[i](k) >= 1.00001]
        if varkeys:
            print "GP iteration %s has relaxed constants" % i
            print sol.program.results[i].table(varkeys)
            if i == len(sol.program.gps) - 1:
                print "WARNING: The final GP iteration had relaxation values greater than 1"
```

**Comment by mayork** [comment]
@bqpd love the speed this gives us but it has broken computing sensitivities to relaxed constants which is pretty critical to what we're doing right now

**Comment by bqpd** [comment]
Ah dang taking a look.

**Comment by bqpd** [comment]
They still work in my tests...I'm doing it a different way now, though. Are you seeing the new `_{before}` constants in your solution tables? Do they have sensitivities?

**Comment by mayork** [comment]
ah okay...but where are those values stores? I'm doing this and it isn't working

```python
sol['sensitivities']
Out[6]: 
{'constants': {},
 'la': array([  1.00000000e+00,   8.06594821e-02,   2.36313415e-03, ...,
          2.76055482e+00,   0.00000000e+00,   2.97970521e+00]),
 'nu': array([  1.00000000e+00,   8.06594821e-02,   2.36313415e-03, ...,
          2.76055482e+00,   0.00000000e+00,   2.97970521e+00])}
```

**Comment by bqpd** [comment]
There should be sensitivities in both the `.results` and the final solution. What file are you running, so I can try to replicate?

**Comment by bqpd** [comment]
Okay, can reproduce. Debugging.

**Comment by mayork** [comment]
I was running the function `run_optimal_D8` from `SP_aircraft.py`...but this seemed to be happening on all my solves from `SP_aircraft.py`

**Comment by bqpd** [comment]
found it, fixing.

**Comment by mayork** [comment]
it's working great now, thanks!!

**Comment by bqpd** [comment]
It gets the sensitivities right (confirmed against master) but doesn't properly map them to the original variables...

**Comment by bqpd** [comment]
Okay, now all the sensitivities are good

**Comment by bqpd** [comment]
@whoburg, merging to bring @mayork and @1ozturkbe back on to master, but hoping to implement this in an even faster way before release, will be writing up some thoughts on the relevant issue.

**Pull request merged**
