### PR TITLE
get build dir from environment variable GPKITBUILD if it exists

### PR DESCRIPTION
**Pull request by bqpd**
@galbramc, see if this fits your needs...

### CODE REVIEW

**Comment by whoburg** [comment]
retest this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
Hmmm, I added GPKITBUILD to the build scripts, but the directory was not created, and the unit tests failed.

**Comment by galbramc** [comment]
I don't see in the build script where you actually create the 'solib_dir' directory. The compiler will not create the directory with the -o switch, at least I don't think it will.

**Comment by galbramc** [comment]
I think you need something like this in build.py

```
        if !os.path.isdir(solib_dir):
            log("# Creating %s" % solib_dir)
            os.makedirs(solib_dir)
```

**Comment by bqpd** [comment]
Oops, you're right. I forgot to also make the GPKITBUILD folder.

**Comment by galbramc** [comment]
This might be why there are problems with pip install as well.

Once this is merged, we can enable full parallel builds.

**Pull request merged**
