### PR TITLE
add x0s to each gp in SP.gps

### LINKED ISSUE #802: access initial guesses of an SP that doesn't solve
is there a way to see the what the initial guess is for an SP solve?

@whoburg also mentioned a way to possibly choose your own initial guess...I'd be really interested in using that on the integrated flight profile and engine model and could help test stuff if that would be helpful

### PR DESCRIPTION
**Pull request by bqpd**
closes #802

### CODE REVIEW

**Comment by bqpd** [comment]
@whoburg ready for review

**Comment by bqpd** [comment]
retest this please

**Comment by whoburg** [comment]
@mayork, FYI - this may be helpful for debugging. you'll be able to do things like `x0s = [gp.x0 for gp in m.program.gps]`.

**Comment by whoburg** [comment]
retest this please

**Pull request merged**
