### PR TITLE
fixes minor typos

### PR DESCRIPTION
**Pull request by pgkirsch**
Couldn't help myself. Ready for merge @bqpd @whoburg.

### CODE REVIEW

**Comment by bqpd** [comment]
Shouldn't it be "recurzively" tho

**Comment by bqpd** [comment]
@galbramc, could you merge this and reset the counter?

**Comment by bqpd** [comment]
None of the lines touched by this PR seem to be much duplicated elsewhere...

**Comment by galbramc** [comment]
I don't have merge privileges.

**Comment by bqpd** [comment]
Oh, huh. Merged!

**Comment by galbramc** [comment]
That's strange...

**Comment by galbramc** [comment]
I reset the counts for the pull requests

**Comment by whoburg** [comment]
Thanks @pgkirsch !

**Pull request merged**
