### PR TITLE
vectorize, environment-based model naming

### PR DESCRIPTION
**Pull request by whoburg**
this enables the performance-model based modeling paradigm.

This needs a review by @whoburg before merging -- creating PR in person with @bqpd

### CODE REVIEW

**Comment by whoburg** [comment]
line 64 of Model should say `if self.name`

**Comment by mayork** [comment]
@bqpd I'm looking at thefile 'performance_modeling_test.py' and one thing I think it lacks, correct me if I'm wrong, is a weight build up between flight segments...i.e. constraining segment weight based on fuel burn.

I'm wondering what our standard procedure for handling this will be inside the vectorized environment? Do we vectorize the flight segments then drill down, extract the weights in each segment, and loop over creating a constraint? Is there a smarter way to do this?

**Comment by mayork** [comment]
also just going to tag @pgkirsch on the off chance this is relevant to his work

**Comment by mayork** [comment]
@bqpd @whoburg I think there's a problem where SignomialEquality can't be vectoried (means the atmosphere can't be vectorized)

When I try and vectorize here's my error

```
Traceback (most recent call last):
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 599, in <module>
    m = Mission(substitutions)
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 490, in __init__
    cls = ClimbSegment(ac)
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 214, in __init__
    self.state = FlightState()
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 226, in __init__
    atm = Atmosphere()
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 295, in __init__
    SignomialEquality(T_sl, T_atm + L_atm*h),
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.py", line 717, in __init__
    SignomialInequality.__init__(self, left, "<=", right)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.py", line 661, in __init__
    ScalarSingleEquationConstraint.__init__(self, left, oper, right)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.py", line 440, in __init__
    self).__init__(Signomial(left), oper, Signomial(right))
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.py", line 74, in __init__
    assert len(cs) == len(exps)
TypeError: object of type 'int' has no len()
```

and the code is at https://github.com/hoburg/gpkit-models/pull/94/commits/058c615887b8c4cbd6a2f762b8c96981f25e1402

**Comment by bqpd** [comment]
oops, yeah, that looks like Signomial Equality's fault.

**Comment by mayork** [comment]
@bqpd what's the status on getting SignomialEquality working with vectorize? Both the engine and atmosphere models require that functionality

**Comment by bjarni177** [comment]
I think the wing box model also requires.

**Comment by bqpd** [comment]
@mayork @bjarni177, it's in now.

```python
import gpkit
from gpkit.constraints.sigeq import SignomialEqualityConstraint

x = gpkit.VectorVariable(3, "x")    
y = gpkit.Variable("y") 

with gpkit.SignomialsEnabled():
    print SignomialEqualityConstraint(x, y)  
```

prints (and is) `\vec{x} = y`

**Comment by whoburg** [comment]
ugh, this has a bunch of old stale commits -- is a rebase in order?

**Comment by mayork** [comment]
@bqpd I pulled and am getting this error when using `SignomialEquality` inside `vectorize`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in <module>()
   1166 
   1167     with vectorize(2):
-> 1168         engineP = engine.dynamic(state)
   1169 
   1170     constraints = []

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in dynamic(self, state)
    129         """
    130         return EnginePerformance(self, self.compressor, self.combustor, self.turbine,
--> 131                                  self.fanmap, self.lpcmap, self.hpcmap, self.thrust, self.sizing, state)
    132 
    133 class Compressor(Model):

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in __init__(self, engine, compressor, combustor, turbine, fanmap, lpcmap, hpcmap, thrust, sizing, state, **kwargs)
   1075         #create the subcomponent performance models
   1076         compP = compressor.dynamic(engine, state)
-> 1077         combP = combustor.dynamic(compP, engine, state)
   1078         turbineP = turbine.dynamic(compP, combP, engine)
   1079         fanmapP = fanmap.dynamic(compP, thrustP)

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in dynamic(self, compressorP, engine, state)
    330         creates an instance of the fan map performance model
    331         """
--> 332         return CombustorPerformance(self, compressorP, engine, state)
    333 
    334 

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in __init__(self, combustor, compressorP, engine, state)
    383 
    384                 #making f+1 GP compatible --> needed for convergence
--> 385                 SignomialEquality(fp1,f+1),
    386                 ])
    387 

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, right)
    715 
    716     def __init__(self, left, right):
--> 717         SignomialInequality.__init__(self, left, "<=", right)
    718         self.oper = "="
    719 

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, oper, right)
    659 
    660     def __init__(self, left, oper, right):
--> 661         ScalarSingleEquationConstraint.__init__(self, left, oper, right)
    662         from .. import SIGNOMIALS_ENABLED
    663         if not SIGNOMIALS_ENABLED:

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, oper, right)
    438     def __init__(self, left, oper, right):
    439         super(ScalarSingleEquationConstraint,
--> 440               self).__init__(Signomial(left), oper, Signomial(right))
    441         self.varkeys = KeySet(self.left.varlocs)
    442         self.varkeys.update(self.right.varlocs)

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, exps, cs, require_positive, simplify, **descr)
     72             try:
     73                 # test for presence of length and identical lengths
---> 74                 assert len(cs) == len(exps)
     75                 exps_ = list(range(len(exps)))
     76                 if not all(isinstance(c, Quantity) for c in cs):

TypeError: object of type 'int' has no len()
```


however, I can successfully run the code you posted above

**Comment by mayork** [comment]
@bqpd I'm now also getting this error inside of `localsolve`. 1 GP iteration will solve to a primal feasible solution and then the error is thrown

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/HT_Simple_Profile_Performance.py in <module>()
    987     m = Mission(substitutions)
    988 ##    sol = m.localsolve(solver='mosek', verbosity = 4)
--> 989     bounds, sol = m.determine_unbounded_variables(m, solver="mosek",verbosity=4, iteration_limit=100)

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/HT_Simple_Profile_Performance.py in determine_unbounded_variables(self, model, solver, verbosity, eps, lower, upper, **kwargs)
    927         "Returns labeled dictionary of unbounded variables."
    928         m = self.bound_all_variables(model, eps, lower, upper)
--> 929         sol = m.localsolve(solver, verbosity, **kwargs)
    930         solhold = sol
    931         lam = sol["sensitivities"]["la"][1:]

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     78         else:
     79             self.program, solvefn = genfunction(self, verbosity)
---> 80             result = solvefn(solver, verbosity, *args, **kwargs)
     81             solution.append(result)
     82         solution.program = self.program

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/signomial_program.pyc in localsolve(self, solver, verbosity, x0, rel_tol, iteration_limit, **kwargs)
    110             self.gps.append(gp)  # NOTE: SIDE EFFECTS
    111             try:
--> 112                 result = gp.solve(solver, verbosity-1, **kwargs)
    113             except (RuntimeWarning, ValueError):
    114                 feas_constrs = ([slackvar >= 1] +

/Users/mayork/Documents/GpGit/gpkit/gpkit/geometric_program.pyc in solve(self, solver, verbosity, *args, **kwargs)
    189 
    190         self._generate_nula(solver_out)
--> 191         result = self._compile_result(solver_out)  # NOTE: SIDE EFFECTS
    192         if verbosity > 1:
    193             print ("result packing took %.2g%% of solve time" %

/Users/mayork/Documents/GpGit/gpkit/gpkit/geometric_program.pyc in _compile_result(self, solver_out)
    275             las = [la[p_i] for p_i in posy_idxs]
    276             nus = [[nu[i] for i in self.m_idxs[p_i]] for p_i in posy_idxs]
--> 277             p_var_senss = constr.sens_from_dual(las, nus)
    278             # ...then add to it the constant sensitivities of each constraint
    279             var_senss += p_var_senss

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in sens_from_dual(self, las, nus)
    258             la = las[offset:offset+n_posys]
    259             nu = nus[offset:offset+n_posys]
--> 260             v_ss = constr.sens_from_dual(la, nu)
    261             var_senss += v_ss
    262             offset += n_posys

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in sens_from_dual(self, la, nu)
    578         # Constant sensitivities
    579         var_senss = {var: sum([presub.exps[i][var]*nu[i] for i in locs])
--> 580                      for (var, locs) in presub.varlocs.items()
    581                      if var in self._last_used_substitutions}
    582         return var_senss

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in <dictcomp>((var, locs))
    579         var_senss = {var: sum([presub.exps[i][var]*nu[i] for i in locs])
    580                      for (var, locs) in presub.varlocs.items()
--> 581                      if var in self._last_used_substitutions}
    582         return var_senss
    583 

/Users/mayork/Documents/GpGit/gpkit/gpkit/keydict.pyc in __contains__(self, key)
     84         if dict.__contains__(self, key):
     85             if idx:
---> 86                 return not np.isnan(dict.__getitem__(self, key)[idx])
     87             return True
     88         elif key in self.keymap:

TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by mayork** [comment]
update - I was importing the wrong signomial equality constriant. I have fixed that but noted that the following line of code

```python

```
SignomialEquality(self.engine['alphap1'], alpha + 1),
```
/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in __init__(self, engine, compressor, combustor, turbine, fanmap, lpcmap, hpcmap, thrust, sizing, state, **kwargs)
   1088         combP = combustor.dynamic(compP, engine, state)
   1089         turbineP = turbine.dynamic(compP, combP, engine)
-> 1090         thrustP = thrust.dynamic(engine, compP, combP, turbineP, state)
   1091         fanmapP = fanmap.dynamic(compP, thrustP)
   1092         LPCmapP = LPCmap.dynamic(compP, thrustP)

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in dynamic(self, compressorP, engine, combustorP, turbP, state)
    768         creates an instance of the thrust performance model
    769         """
--> 770         return ThrustPerformance(self, engine, compressorP, turbP, combustorP, state)
    771 
    772 class ThrustPerformance(Model):

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/aircraft/CFM_56_performance_components.py in __init__(self, thrust, compressorP, engine, turbP, combustorP, state)
    854                 alpha == mFan / mCore,
    855                 hold == self.engine['alphap1'],
--> 856                 SignomialEquality(self.engine['alphap1'], alpha + 1),
    857                 alpha <= 5.105,
    858 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/sigeq.pyc in __init__(self, left, right)
     12             constraints = sigeq_vectorized(left, right)
     13         else:
---> 14             constraints = [SignomialEquality(left, right)]
     15         ConstraintSet.__init__(self, constraints)

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, right)
    715 
    716     def __init__(self, left, right):
--> 717         SignomialInequality.__init__(self, left, "<=", right)
    718         self.oper = "="
    719 

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, oper, right)
    659 
    660     def __init__(self, left, oper, right):
--> 661         ScalarSingleEquationConstraint.__init__(self, left, oper, right)
    662         from .. import SIGNOMIALS_ENABLED
    663         if not SIGNOMIALS_ENABLED:

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, left, oper, right)
    438     def __init__(self, left, oper, right):
    439         super(ScalarSingleEquationConstraint,
--> 440               self).__init__(Signomial(left), oper, Signomial(right))
    441         self.varkeys = KeySet(self.left.varlocs)
    442         self.varkeys.update(self.right.varlocs)

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in __init__(self, exps, cs, require_positive, simplify, **descr)
     72             try:
     73                 # test for presence of length and identical lengths
---> 74                 assert len(cs) == len(exps)
     75                 exps_ = list(range(len(exps)))
     76                 if not all(isinstance(c, Quantity) for c in cs):

TypeError: object of type 'int' has no len()
```

the `SignomialEquality` works if I use this code

```
hold == self.engine['alphap1'],
SignomialEquality(hold, alpha + 1),
```

**Comment by mayork** [comment]
@bqpd 

now I'm getting this error when I try and use localsolve

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/HT_Simple_Profile_Performance.py in <module>()
    987     m = Mission(substitutions)
    988 ##    sol = m.localsolve(solver='mosek', verbosity = 4)
--> 989     bounds, sol = m.determine_unbounded_variables(m, solver="mosek",verbosity=4, iteration_limit=100)

/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/HT_Simple_Profile_Performance.py in determine_unbounded_variables(self, model, solver, verbosity, eps, lower, upper, **kwargs)
    927         "Returns labeled dictionary of unbounded variables."
    928         m = self.bound_all_variables(model, eps, lower, upper)
--> 929         sol = m.localsolve(solver, verbosity, **kwargs)
    930         solhold = sol
    931         lam = sol["sensitivities"]["la"][1:]

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     78         else:
     79             self.program, solvefn = genfunction(self, verbosity)
---> 80             result = solvefn(solver, verbosity, *args, **kwargs)
     81             solution.append(result)
     82         solution.program = self.program

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/signomial_program.pyc in localsolve(self, solver, verbosity, x0, rel_tol, iteration_limit, **kwargs)
    107     appear to be converging, you may wish to increase the iteration limit by
    108     calling .localsolve(..., iteration_limit=NEWLIMIT).""" % len(self.gps))
--> 109             gp = self.gp(x0, verbosity=verbosity-1)
    110             self.gps.append(gp)  # NOTE: SIDE EFFECTS
    111             try:

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/signomial_program.pyc in gp(self, x0, verbosity)
    152         """Get a GP approximation of this SP at x0"""
    153         x0 = self._default_x0(x0) if x0 is None else x0
--> 154         gp = GeometricProgram(self.cost, self.as_gpconstr(x0),
    155                               self.substitutions, verbosity=verbosity)
    156         gp.x0 = KeyDict(x0)  # NOTE: SIDE EFFECTS

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.pyc in as_gpconstr(self, x0)
    267 
    268         When x0 is none, may return a default guess."""
--> 269         gpconstrs = [constr.as_gpconstr(x0) for constr in self]
    270         return ConstraintSet(gpconstrs, self.substitutions)
    271 

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in as_gpconstr(self, x0)
    705         siglt0, = self.unsubbed
    706         posy, negy = siglt0.posy_negy()
--> 707         x0.update({vk: 1.0 for vk in negy.varlocs if vk not in x0})
    708         pc = PosynomialInequality(posy, "<=", negy.mono_lower_bound(x0))
    709         pc.substitutions = self.substitutions

/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.pyc in <dictcomp>((vk,))
    705         siglt0, = self.unsubbed
    706         posy, negy = siglt0.posy_negy()
--> 707         x0.update({vk: 1.0 for vk in negy.varlocs if vk not in x0})
    708         pc = PosynomialInequality(posy, "<=", negy.mono_lower_bound(x0))
    709         pc.substitutions = self.substitutions

/Users/mayork/Documents/GpGit/gpkit/gpkit/keydict.pyc in __contains__(self, key)
     84         if dict.__contains__(self, key):
     85             if idx:
---> 86                 return not np.isnan(dict.__getitem__(self, key)[idx])
     87             return True
     88         elif key in self.keymap:

TypeError: 'float' object has no attribute '__getitem__'
```

**Comment by mayork** [comment]
@bqpd is there a local work around for these type errors? I think its become a bottle neck in the D8 modeling

**Comment by bqpd** [comment]
Type errors were from substituting scalars for vector variables.

**Comment by bqpd** [comment]
Signomial Equality error was Pints breaking our operator overloading. Quantities are incompatible right now with NomialArrays, and should be replaced by Variables (good practice in general)

**Comment by mjburton11** [comment]
Even thouh my code runs, I'm getting the pylint error:

```[unsubscriptable-object] Value 'Sbar' is unsubscriptable```

on all my variables that I declare with `vectorize`.  This is the chunk of code:
```python
          with vectorize(N-1):
              EIbar = Variable("\\bar{EI}", "-",
                               "normalized YM and moment of inertia")
  
          with vectorize(N):
              Sbar = Variable("\\bar{S}", "-", "normalized shear")
              Mbar = Variable("\\bar{M}", "-", "normalized moment")
              th = Variable("\\theta", "-", "deflection slope")
              dbar = Variable("\\bar{\\delta}", "-", "normalized displacement")
  
  
          Sbar_tip = Variable("\\bar{S}_{tip}", 1e-10, "-", "Tip loading")
          Mbar_tip = Variable("\\bar{M}_{tip}", 1e-10, "-", "Tip moment")
          th_root = Variable("\\theta_{root}", 1e-10, "-", "Base angle")
          dbar_root = Variable("\\bar{\\delta}_{root}", 1e-10, "-",
                               "Base deflection")
          dx = Variable("dx", "-", "normalized length of element")
  
          constraints = [
>>            Sbar[:-1] >= Sbar[1:] + 0.5*dx*(state["\\bar{q}"][:-1] +
                                              state["\\bar{q}"][1:]),
>>            Sbar[-1] >= Sbar_tip,
>>            Mbar[:-1] >= Mbar[1:] + 0.5*dx*(Sbar[:-1] + Sbar[1:]),
>>            Mbar[-1] >= Mbar_tip,
>>            th[0] >= th_root,
>>            th[1:] >= th[:-1] + 0.5*dx*(Mbar[1:] + Mbar[:-1])/EIbar,
>>            dbar[0] >= dbar_root,
>>            dbar[1:] >= dbar[:-1] + 0.5*dx*(th[1:] + th[:-1]),
              1 == (N-1)*dx,
>>            EIbar <= static["E"]*static["I"]/state["N_{max}"]/state["W_{cent}"  ]*static["b"]/(static["b"]/2)**3,
              static["\\sigma_{CFRP}"] >=
>>            ((Mbar[:-1] + Mbar[1:])/2*static["b"]*state["W_{cent}"]*state["N_{  max}"]/4*(static["h_{in}"]+static["t"])/static["I"]),
>>            dbar[-1] <= state["\\kappa"],

```

**Comment by bqpd** [comment]
Heh. I can see why Pylint would think that...there's probably two fixes for
this. 1) make Variable inherit from a subscriptable object; 2) remove this
error from our pylint.

**Comment by whoburg** [comment]
Can someone help @arthur-brown get up to speed with use of this branch? is `performance_modeling_test.py` still the right place to start?

What is the plan for the merge conflicts?

**Comment by mayork** [comment]
@whoburg @bqpd when will this be merged into master? After debugging my engine performance model to no avail for quite some time I realized that none of the engine models solve on this branch (it seems pretty far behind master)

**Comment by bqpd** [comment]
@mayork, try the `newvectorized` branch (https://github.com/hoburg/gpkit/pull/941)

**Comment by bqpd** [comment]
Closing this PR because it's superseded by the combination of https://github.com/hoburg/gpkit/pull/941 and https://github.com/hoburg/gpkit/pull/941

**Comment by whoburg** [comment]
@bqpd I think you meant the combination of #941 and something else?

**Comment by bqpd** [comment]
whoops, yeah. I meant #920, but it looks like that doesn't actually include the change from `process_result` to `process_solution` :-/ looking into it.

**Pull request closed without merging**
