### PR TITLE
get apidocs building on sphinx and macs

### LINKED ISSUE #752: can't build docs
Commit add9d6093bc48e4ae21b5378fe0b60b4d6715e2c broke `make html` on my mac. `make html` runs fine on the parent commit, whereas after the commit above I get:

```
whoburg$ make html
rm source/autodoc/*
sphinx-apidoc ../gpkit -o source/autodoc
Creating file source/autodoc/gpkit.rst.
Creating file source/autodoc/gpkit.constraints.rst.
Creating file source/autodoc/gpkit.interactive.rst.
Creating file source/autodoc/gpkit.nomials.rst.
Creating file source/autodoc/gpkit.tests.rst.
Creating file source/autodoc/gpkit.tools.rst.
Creating file source/autodoc/modules.rst.
sed -i '1i Glossary\n********\n\n*For an alphabetical listing of all commands, check out the* :ref:`genindex`\n' source/autodoc/gpkit.rst
sed: 1: "source/autodoc/gpkit.rst": bad flag in substitute command: 'c'
make: *** [apidoc] Error 1
```

### PR DESCRIPTION
**Pull request by bqpd**
closes #752

### CODE REVIEW

**Comment by bqpd** [comment]
Ignore the pylint warnings. @galbramc, all branches are currently seeing 6 warnings fixed in another branch. What's happened?

**Comment by galbramc** [comment]
The counts got reset when you created PR with some pylint fixes. We have to reset the counts or merge that PR with the fixes.

**Comment by bqpd** [comment]
Please reset for now, then; this is blocking three different PRs...

**Comment by bqpd** [comment]
...I definitely have removing all the pylint errors in master on the list so this doesn't happen again :p

**Comment by galbramc** [comment]
Yeah, I've spent the morning trying to find a workaround, but I can't find anything that would proved a simple solution to the problem. The simplest thing to do is just fix/suppress pylint warnings. That is the best long term solution regardless of what ever workaround I could come up with right now.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
I think the best thing I could do right now would be to help fix some of the really simple pylint warnings. @whoburg, would you be ok with that? This would be the trivial line to long and unused variable type warnings that I could simply fix. The more warnings are fixed the simpler it will be to avoid this problem in the future.

**Comment by bqpd** [comment]
That sounds great! I can jump in and close other types. Should we do it as one PR?

**Comment by galbramc** [comment]
Yes, doing one PR would be the best. If we can just squash the simple ones it will really help prevent this from happening. If you want to setup the PR I can check it out and squash the simple ones first.

**Comment by bqpd** [comment]
done in https://github.com/hoburg/gpkit/pull/841

**Comment by whoburg** [comment]
re: this PR, it isn't working on my mac; maybe @bqpd wants to debug on my machine? @mayork and @mjburton11 also have macs...

**Comment by bqpd** [comment]
I'll be meeting with mjburton this afternoon, if we find the time I'll do it then.

**Comment by galbramc** [comment]
Do you guys want this to be part of your testing? We could make another jenkins job to make sure your documentation is always working on all testing platforms?

**Comment by whoburg** [comment]
@galbramc's latest commit runs for me on my mac (!) and also runs for @galbramc on Ubuntu.

Remaining related issue is #501.

**Comment by bqpd** [comment]
Beautiful!

**Comment by bqpd** [comment]
This should fix 501. Merge it and see if it builds on rtfd?

**Comment by whoburg** [comment]
Don't think it would fix #501, but @galbramc is about to push a commit that will :)

**Comment by whoburg** [comment]
Thanks @galbramc !!!

**Pull request merged**
