### PR TITLE
Fixes in build.py for Windows

### PR DESCRIPTION
**Pull request by galbramc**
This should fix the builds on the Windows 10 VM

### CODE REVIEW

**Comment by galbramc** [comment]
test this please

**Comment by bqpd** [comment]
Oh, good catch! It seems to still not be working?

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
It's working on windows 10 now, but windows 7 is broken because I followed the recommended install process where python(x,y) is the prefered version of python. Python(x,y) is only 32 bit, so mosek must be 32 bit, but the build script is not setup to find the 32 bit mosek. I'm trying to fix that now.

**Comment by galbramc** [comment]
@bqpd @whoburg all testing on the windows machines will fail until this is merged. Please review and adjust to your liking.

We will also need to reset the pylint warnings, as this is the last file with a bazillion of them...

**Comment by bqpd** [comment]
@whoburg, I'm ready to merge this.

**Comment by whoburg** [comment]
sounds good. @galbramc and I are going to fix some pylint errors before merging

**Pull request merged**
