### PR TITLE
assorted pylint tweaks

### PR DESCRIPTION
**Pull request by whoburg**
- increase max branches from 12 to 15
 - line length 80 char
 - docstrings not required for unit test methods

### CODE REVIEW

**Comment by whoburg** [comment]
yarg... @galbramc I decreased the max line length and now I want to get this on master

**Comment by galbramc** [comment]
All we need to do is reset the reference on both the pull request build and the push build. If you are happy with these settings you can go ahead and merge, and then we just reset the counts like I showed you.

**Comment by galbramc** [comment]
Did you look at the number of methods restriction? There are also things about not defining all variables in the init method that pylint warns about.

**Comment by whoburg** [comment]
ok will look at that some other time, too many other fires buring

**Pull request merged**
