### PR TITLE
A more useful plot_convergence

### PR DESCRIPTION
**Pull request by pgkirsch**
Only plots cost convergence instead of trying to plot variables convergence

Ready for review @whoburg  @bqpd

### CODE REVIEW

**Comment by pgkirsch** [comment]
(Bump)


(Should be a really easy review)

**Comment by bqpd** [comment]
Attach an example plot and I'll merge it. :D

**Comment by pgkirsch** [comment]
convergence_wi

How's this?

**Comment by bqpd** [comment]
:+1:

**Comment by whoburg** [comment]
sweet. minor design discussion: should we plot this on a semilogy scale?

**Comment by bqpd** [comment]
Hmm! I'd argue no; we're checking the effects of negynomials, which I wouldn't expect to span too many orders of magnitude?

**Comment by bqpd** [comment]
Actually, gonna change my mind and argue yes, since the terminating distinction is reltol...

**Comment by pgkirsch** [comment]
The downside being a lot of these plots end up being flat on a semiology scale (as suggested by @bqpd)

**Comment by bqpd** [comment]
Can't we autoscale the y axis to prevent that?

**Comment by pgkirsch** [comment]
Hm, yes. But why does the log scale help in this case?

On May 14, 2016, at 12:19, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't we autoscale the y axis to prevent that?

**Comment by bqpd** [comment]
Oh, because the sp solve terminates when the previous solution is close enough to the current solution in  logspace, so plotting that directly might be more easily readable?

**Comment by bqpd** [comment]
Clearly there's arguments both ways, though. :p

**Comment by pgkirsch** [comment]
Well then perhaps it makes most sense to plot the absolute difference from the final cost. Otherwise I'm not sure you can "see" the convergence condition being satisfied.

On May 14, 2016, at 12:25, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


Clearly there's arguments both ways, though. :p

**Comment by bqpd** [comment]
Hmm, any multiplicative distance (like reltol) should show up as a fixed delta-y.

**Pull request merged**
