### PR TITLE
allow appending to a constraintset

### PR DESCRIPTION
**Pull request by bqpd**
example code from @mjburton11 

```python
" wing.py "
import numpy as np
from gpkit import Variable, Model, SignomialsEnabled, ConstraintSet
from gpkitmodels.GP.aircraft.wing.wing import Wing as WingGP
from gpkit import Variable, Model, Vectorize, SignomialsEnabled

# pylint: disable=attribute-defined-outside-init, invalid-name


def Wingtest(N=5, lam=0.5, spar="CapSpar", hollow=False):
    wing = WingGP(N=N, lam=lam, spar=spar, hollow=hollow)
    mw = Variable("m_w", "-", "span wise effectiveness")

    with SignomialsEnabled():
        constraints = [mw*(1 + 2/wing["AR"]) >= 2*np.pi]

    wing.append(constraints)
    return wing

w = Wingtest()
print w["m_w"]
```

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
retest this please

**Comment by mjburton11** [comment]
@bqpd what's the status on this?

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
merging so that gassolar passes tests. @whoburg, ready for review

**Pull request merged**
