### PR TITLE
Cleaner tight constraint message

### PR DESCRIPTION
**Pull request by pgkirsch**
Addresses issue #691 

Ready for review @whoburg @bqpd

### CODE REVIEW

**Comment by bqpd** [comment]
Any idea why this is failing tests?

**Comment by pgkirsch** [comment]
Hmm @bqpd is there something like `.magnitude` that works for both variables with units and without units? Seems to be causing the the units tests to fail.

**Comment by bqpd** [comment]
Yes! Use the `mag` function from `small_scripts`

**Comment by pgkirsch** [comment]
eurgh I was worried you would say that :P

**Comment by pgkirsch** [comment]
Should be good to go

**Comment by whoburg** [comment]
retest this please

**Pull request merged**
