### PR TITLE
add test for #1131

### PR DESCRIPTION
**Pull request by bqpd**
as requested in #1133. @whoburg, ready for review

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by whoburg** [comment]
so, an alternative proposal would be to throw an error when the user sets the cost to a fixed variable. Note there's a delicate issue here in that we should still support feasibility solves (where the cost is a constant). So to be a bit more refined, we should throw the error when solving a model where (the cost is set to a fixed variable AND the fixed variable's value does not appear in the model's substitutions).

**Comment by mjburton11** [comment]
@whoburg the example you posted is actually the use case I want.  For example, in JHO my initial value for `t_Loiter` is 6 days.  But I want to delete that substitution and make `t_Loiter` the objective.

**Comment by whoburg** [comment]
The discussion above occurred after this got merged -- did the issue about cost being a fixed variable get captured somewhere?

**Comment by bqpd** [comment]
It's come up again in a few discussions of how to handle substitutions, particularly #1237 and #1218

In general, the cost may contain substitutions that aren't contained anywhere else -- this is the best way to implement composite objectives, for example. We could ban that easily, but I think it's better to just 'pop' values after their use, as in #1237

**Pull request merged**
