### PR TITLE
Adds the unit of g's

### PR DESCRIPTION
**Pull request by pgkirsch**
Adding units of g's (well, actually, G's) so that people can express acceleration in terms of [earth's] gravitational acceleration.

`g` obviously means grams primarily, so opting for uppercase `G` as the next best option.

I've run this past @bqpd. What do you think @whoburg?

### CODE REVIEW

**Comment by whoburg** [comment]
I like it, but I'd propose that you submit it as a PR to pint (https://github.com/hgrecco/pint/) first? That's the cleaner place for this to happen.

**Comment by whoburg** [comment]
also not sure about `G`, which is usually reserved for the gravitational constant. What about gs or Gs?

**Comment by whoburg** [comment]
see https://github.com/hgrecco/pint/pull/534

**Comment by pgkirsch** [comment]
Cool, thanks for creating that PR for me. Did you already create another PR for nautical miles previously?

**Comment by whoburg** [comment]
see https://github.com/hgrecco/pint/issues/366 and https://github.com/hgrecco/pint/pull/367.

**Comment by pgkirsch** [comment]
Perfect. So given that nmi is in __init__.py as a holdover, is the plan do the same for gs until it is released in pint?

**Comment by whoburg** [comment]
If you'd use it, I'd be willing to approve it. Please change the numerical value and names to match the pint PR, and request a review (tag me with @ so I know to review).

**Comment by pgkirsch** [comment]
@whoburg ready for a quick final review

**Comment by whoburg** [comment]
test models please

**Comment by whoburg** [comment]
Actually, I just realized that pint already supports this:

`pint/constants_en.txt:standard_gravity = 9.806650 * meter / second ** 2 = g_0 = g_n = gravity`

Here's an example of using in GPkit:

```python
In [1]: from gpkit import units

In [2]: accel = 0.5*units("m/s/s")

In [3]: accel.to("standard_gravity")
Out[3]: gpkit.Monomial(0.051 [g_0])

In [4]: accel.to("gravity")
Out[4]: gpkit.Monomial(0.051 [g_0])

In [5]: accel.to("g_0")
Out[5]: gpkit.Monomial(0.051 [g_0])
```

In light of that, my vote is to close this without merging.

**Comment by whoburg** [comment]
One more example that currently works without this PR:

```python
In [7]: from gpkit import Variable

In [8]: a = Variable("a", 0.5, "gravity", "acceleration")

In [9]: a.units
Out[9]: <Quantity(1, 'standard_gravity')>
```

**Comment by pgkirsch** [comment]
Huh, well that's awesome. Sorry I didn't find that before. Agree with closing without merge, obviously.

**Pull request closed without merging**
