### PR TITLE
allow GP solves to return near_dual_feas solutions

### LINKED ISSUE #1048: How to handle NEAR_OPTIMAL solution status
As mentioned in #1047 I have a model (at commit 184467c058267d1fefa1 on the D8 repo) that returns

```
Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : NEAR_OPTIMAL
  Primal.  obj: 1.1998763649e+01    Viol.  con: 3e-02    var: 0e+00  
  Dual.    obj: 1.2009877944e+01    Viol.  con: 0e+00    var: 7e-02  
* End solution on dual form. *
```

The NEAR_OPTIMAL occurs during the first GP solve. We then do a feasibility solve, which I'm not sure makes sense. More generally, Woody and I weren't sure how to handle and solve that returns NEAR_OPTIMAL.

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1048 

@whoburg, ready for review

### CODE REVIEW

**Comment by mayork** [comment]
thanks @bqpd! this seems to have increased our solution reliability

**Comment by mayork** [comment]
@1ozturkbe run your code on this branch and it should work

**Comment by mayork** [comment]
also, I think the D8 repo will start reliably passing tests once this is merged to master

**Comment by mayork** [comment]
@bqpd i added a warning message to this

**Comment by mayork** [comment]
@whoburg ready for rereview

**Comment by mayork** [comment]
@whoburg hold off going to add a unit test

**Comment by mayork** [comment]
@whoburg this is ready for review the unit test can't be written until relaxed constants solution heuristic is added to gpkit. once this is merged i will made an issue to add the requisite unit test so we don't forget

**Comment by mayork** [comment]
also...I think that D8 will pass tests once this is merged

**Comment by bqpd** [comment]
@mayork that other branch is merged, this is ready for a test!

**Comment by mayork** [comment]
now that I think about this, I think it's better without a test4. For one, I've only been able to generate near optimal in large signomial programs (>1,500 variables) and I don't think we want our tests to run slow because of this one units test. Further, near_optimal is returned non-deterministically so I'm not sure a good test can be formulated regardless of speed.

**Comment by bqpd** [comment]
interesting point. I just saw it yesterday with one of Ali's robust GPs, maybe we should use that as a test instead?

**Comment by mayork** [comment]
Yeah that seems like a better test. if you post a commit hash I can build a test.

**Comment by whoburg** [comment]
test models please

**Comment by whoburg** [comment]
Looks good to me. I added one commit. This looks ready to merge once it passes tests.

**Comment by mayork** [comment]
@bqpd can this be merged? It'd get the full D8 suite running back on master

**Comment by mayork** [comment]
i added a few more aircraft models to the D8 tests....it will pass once this is merged to master

**Comment by bqpd** [comment]
Merging, will create issue for test.

**Pull request merged**
