### PR TITLE
Fix sed bug on OS X

### LINKED ISSUE #1095: stray rst-e file appears when building docs
Every time I build the html version of the docs, a file `docs/source/autodoc/gpkit.rst-e` appears. Is this local to my machine, or can others reproduce?

### PR DESCRIPTION
**Pull request by edfan**
Fixes #1095

### CODE REVIEW

**Comment by whoburg** [comment]
add to whitelist

**Comment by whoburg** [comment]
@edfan you are now on the whitelist so Jenkins should automatically test any PR you submit

**Comment by whoburg** [comment]
@bqpd can you please confirm this still works on GNU?

@edfan thanks this looks great

**Comment by whoburg** [comment]
@bqpd will squash and merge once he confirms this still works on GNU

**Comment by whoburg** [comment]
test models please

**Comment by edfan** [comment]
Tested on GNU (Ubuntu 16.04 LTS)- this breaks sed with `sed: can't read : No such file or directory`. Looks like it might not be possible to maintain OS X and GNU compatability, as OS X wants `sed -i '' -e` and GNU wants `sed -i -e`. See [here](https://unix.stackexchange.com/a/131940).

Better to just use tail, instead.

**Comment by bqpd** [comment]
"Use sed," he thought. "It's basically part of POSIX."

(using tail sounds like a great plan)

**Pull request closed without merging**
