### PR TITLE
Proposed fix to issue #561

### PR DESCRIPTION
**Pull request by pgkirsch**
ready for review @whoburg @bqpd

### CODE REVIEW

**Comment by bqpd** [comment]
Looks good to me; ready to merge after @whoburg review and it passes tests.

**Comment by whoburg** [comment]
I'm going to make a few tweaks on this branch

**Comment by whoburg** [comment]
@pgkirsch or @bqpd, added commits, ready for review.

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
@galbramc -- https://acdl.mit.edu/csi/job/gpkit_PullRequest_Depends/425/ was a surprising failure -- nothing changed between that and https://acdl.mit.edu/csi/job/gpkit_PullRequest_Depends/426/.

**Comment by galbramc** [comment]
So this was multiple versions of pip trying to write to the pip cache at the same time because of the new version of ipywidgets. I can think of a couple of ways to solve this, but I'm not sure what the best option is. Are you around to talk about it?

**Comment by galbramc** [comment]
Actually... I think I have the right solution. I was sharing the pip cache, I'm going to just make sure each entry in the matrix has it's own cache. I'm going to have to rebuild the caches though, so there is going to be a very long build here for a moment.

**Comment by bqpd** [comment]
Ready to merge, @whoburg ?

**Comment by whoburg** [comment]
@bqpd, yes, I'm ready for you to merge, if you're happy with the commits I added.

**Pull request merged**
