### PR TITLE
update install instructions with recommendations from @galbramc

### PR DESCRIPTION
**Pull request by whoburg**
This is ready for review and could use some work from someone with a good eye for graphics / markdown.

### CODE REVIEW

**Comment by galbramc** [comment]
I wonder if you should mention something about installing in your system vs as a user. Technically you need to run "sudo pip install" on OS X and Linux to install things into the system. Otherwise you should run "pip install --user" to just install for a user. Not sure what the easiest way is to document this.

**Comment by galbramc** [comment]
I wonder if you should mention something about installing in your system vs as a user. Technically you need to run "sudo pip install" on OS X and Linux to install things into the system. Otherwise you should run "pip install --user" to just install for a user. Not sure what the easiest way is to document this.

**Comment by galbramc** [comment]
I think we need to update the "unintstall" instructions, or instructions when you install a new solver. Currently the settings file gets saved in the cache, that means you only get the solvers you have the first time you install gpkit. Any subsequent times you run pip it will simply restore the cached settings file, even if you have installed other solvers since then. I think we should tell people to blow away the cache:

Linux
find ~/.cache/pip/wheels/ -name "*gpkit*" -delete

OS X
find ~/Library/Caches/pip/wheels -name "*gpkit*" -delete

Windows
C:\Users\(your_user_name)\AppData\Local\pip\cache\wheels
Search for gpkit and delete any files with the name gpkit*.whl

**Comment by galbramc** [comment]
test this please

**Comment by whoburg** [comment]
@galbramc thanks -- are you sure the cache needs to be deleted even with the `--no-cache-dir` option for `pip install`?

**Comment by galbramc** [comment]
Well, you can either tell people to delete the cache, or recommend that they use ```--no-cache-dir``` absolutely every time they install gpkit. This is really a hole in pip that there is no easy way to force a "rebuild".

**Comment by whoburg** [comment]
OK thanks -- we think our "rebuild GPkit" instructions are correct since they list --no-cache-dir

**Comment by galbramc** [comment]
Yes, but it can be deceptive

install cvxopt
install gpkit
uninstall gpkit
install mosek
install gpkit  --no-cache-dir
unisntall gpkit
install gpkit      <-- only gets cvxopt because that's what was in the cache

the last install lost mosek because gpkit was restored from the cache

**Comment by galbramc** [comment]
I think the right thing to do really is the blow away the cache. It's the most robust solution.

**Comment by galbramc** [comment]
Though it's the most awkward solution.

**Comment by galbramc** [comment]
Maybe if you put the settings file in .gpkit rather than gpkit/env. That might solve the problem. Then suggesting --no-cache-dir would work correctly.

**Pull request merged**
