### PR TITLE
Fmincon improvements

### PR DESCRIPTION
**Pull request by pgkirsch**
Improved tool for generating `fmincon` code, as used in the final version of my thesis.

Changes include:
- auto-generating initial guesses given the type of initial guess requested
- Specifying things like the algorithm to use and whether or not to use gradients as kwargs

Ready for review @whoburg @bqpd

### CODE REVIEW

**Comment by bqpd** [comment]
Looks good! Want to document some example usages in this PR thread?

**Comment by pgkirsch** [comment]
Sure. You mean example auto-generated .m files?

**Comment by bqpd** [comment]
Yeah! And any benchmarks you already made, no need to make new ones just
for this purpose.

**Comment by pgkirsch** [comment]
`fmincon.generate_mfiles` generates 4 files: 3 .m files (`main.m`, `confun.m`, `objfun.m`) and 1 .txt file (`lookup.txt`). For the `simpleflight` model, using default inputs, these look as follows:

main.m
----------
```matlab
x0 = ones(10,1);
options = optimset('fmincon');
options.Algorithm = 'interior-point';
options.MaxFunEvals = Inf;
options.MaxIter = Inf;
options.GradObj = 'on';
options.GradConstr = 'on';
tic;
[x,fval] = ...
fmincon(@objfun,x0,[],[],[],[],[],[],@confun,options);
elapsed = toc;
fid = fopen('elapsed.txt', 'w');
fprintf(fid, '%.1f', elapsed);
fclose(fid);
fid = fopen('cost.txt', 'w');
fprintf(fid, '%.5g', fval);
fclose(fid);
```

objfun.m
----------
```matlab
function [f, gradf] = objfun(x)
f = x(4);
if nargout > 1
    gradf  = [0
              0
              0
              1
              0
              0
              0
              0
              0
              0];
end
```

confun.m
-----------
```matlab
function [c, ceq, DC, DCeq] = confun(x)
% Nonlinear inequality constraints
c = [
    -x(1) + 0.031*x(6).^-1 + 0.335*x(3).^-1*x(5).^2 + 2.46*x(10)
    -x(2) + 0.194*x(3).^1.5*x(6).^0.5*x(8).^0.5 + 45.2*x(6)
    -6.91e+04*x(3).^-0.5*x(6).^0.5*x(9) + x(7)
    -x(10) + 0.074*x(7).^-0.2
    -0.615*x(5)*x(6)*x(9).^2 + x(8)
    -446*x(6) + x(8)
    -x(8) + 4.94e+03 + x(2)
    ];

ceq = [
      -x(4) + 0.615*x(1)*x(6)*x(9).^2
      ];
if nargout > 2
    DC = [
          -1,...
          0,...
          -0.335*x(3).^-2*x(5).^2,...
          0,...
          0.67*x(3).^-1*x(5),...
          -0.031*x(6).^-2,...
          0,...
          0,...
          0,...
          2.46;
          0,...
          -1,...
          0.291*x(3).^0.5*x(6).^0.5*x(8).^0.5,...
          0,...
          0,...
          0.0969*x(3).^1.5*x(6).^-0.5*x(8).^0.5 + 45.2,...
          0,...
          0.0969*x(3).^1.5*x(6).^0.5*x(8).^-0.5,...
          0,...
          0;
          0,...
          0,...
          3.46e+04*x(3).^-1.5*x(6).^0.5*x(9),...
          0,...
          0,...
          -3.46e+04*x(3).^-0.5*x(6).^-0.5*x(9),...
          1,...
          0,...
          -6.91e+04*x(3).^-0.5*x(6).^0.5,...
          0;
          0,...
          0,...
          0,...
          0,...
          0,...
          0,...
          -0.0148*x(7).^-1.2,...
          0,...
          0,...
          -1;
          0,...
          0,...
          0,...
          0,...
          -0.615*x(6)*x(9).^2,...
          -0.615*x(5)*x(9).^2,...
          0,...
          1,...
          -1.23*x(5)*x(6)*x(9),...
          0;
          0,...
          0,...
          0,...
          0,...
          0,...
          -446,...
          0,...
          1,...
          0,...
          0;
          0,...
          1,...
          0,...
          0,...
          0,...
          0,...
          0,...
          -1,...
          0,...
          0
         ]';
    DCeq = [
            0.615*x(6)*x(9).^2,...
            0,...
            0,...
            -1,...
            0,...
            0.615*x(1)*x(9).^2,...
            0,...
            0,...
            1.23*x(1)*x(6)*x(9),...
            0
           ]';
end
```

lookup.txt
-----------
```
x_1: C_D
x_2: W_w
x_3: A
x_4: D
x_5: C_L
x_6: S
x_7: Re
x_8: W
x_9: V
x_10: C_f
```

**Comment by pgkirsch** [comment]
See chapter 9 of my thesis for benchmarks ;)

**Comment by bqpd** [comment]
;) perfect, ready to commit once @whoburg has reviewed

**Comment by whoburg** [comment]
this is pretty sweet.

**Pull request merged**
