### PR TITLE
Fix remote skipsolvers

### PR DESCRIPTION
**Pull request by bqpd**
@whoburg, ready for review. No longer high priority.

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
test models please

**Comment by galbramc** [comment]
Why is this trying to use mosek?

https://acdl.mit.edu/csi/job/gpkit_PullRequest_Models/buildnode=macys_Sierra,optimizer=cvxopt/23/console

This build should only have cvxopt as the installed solver.

**Comment by bqpd** [comment]
Because mosek is explicitly declared as the solver, and gpkit doesn't check
whether it was found at install time before trying to use mosek...

**Comment by galbramc** [comment]
So people need to add explicit statements to the test in regards to which solver they use? Is this a gpkit problem or a ResearchModel TESTS problem.

**Comment by bqpd** [comment]
About to merge branches on the research repositories that fix this.

**Comment by galbramc** [comment]
All, thats what those PRs were for, that sounds good.

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
Oh I forgot. You need to add --no-deps as well only to the local install command. So only with -e do you want --no-cache-dir --no-deps. Otherwise pip downloads all are recompiles all the dependencies as well. Which is why it is taking extra long for this model test.

**Comment by bqpd** [comment]
whoops! wildo.

**Comment by galbramc** [comment]
You should change it so --no-cache-dir also only shows up for the local install.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
You can't use both --no-cache-dir and --no-deps

**Comment by galbramc** [comment]
Oh yes you can. We are using both of those. If you don't use --no-deps with --no-cache, it will download and recompile all dependencies, because it can't find them in the cache. So you need to use them together.

**Comment by bqpd** [comment]
Yeah, just realized -e had to be last...

**Comment by galbramc** [comment]
Ahh, that I can believe. I'm guessing path is an input to -e

**Comment by bqpd** [comment]
Seems like.

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
One more thing. None of the repository tests are registering any coverage information. This seems to be a solution to the problem, 

http://stackoverflow.com/questions/33707441/code-coverage-does-not-cover-dynamically-imported-packages-modules/33707948

which suggest just a slight modification to use the __import__() function instead. Then you will have coverage information for all the ResearchModel tests as well.

**Comment by bqpd** [comment]
I'm already using importlib and the import function, hmm.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
Unfortunately we will not know if this fixed the coverage until this is merged. The two pending test did pass, not sure why jenkins didn't update the statues. I had some issues with the github plugin before, so I just downgraded it back to what seamed to be a stable version. I would say this is ready to be merged in my humble opinion.

**Comment by galbramc** [comment]
test models please

**Comment by galbramc** [comment]
test gpkit please

**Comment by bqpd** [comment]
Okay, let's merge and see if this fixes coverage on the research repo tests!

**Comment by bqpd** [comment]
@galbramc, this doesn't seem to have triggered d8_Push etc?

**Comment by bqpd** [comment]
manually triggered repo tests, doesn't seem to have fixed coverage.

**Comment by galbramc** [comment]
Yeah I know. There is something with authorization that even though as best as I can tell I have configured correctly, is preventing downstream builds from getting triggered.

Yeah I saw it didn't fix the coverage either... You might need to dig some more on that if you want coverage on the Research Models, which is really good to have.

**Comment by bqpd** [comment]
Will do, that would be good to have.

**Comment by galbramc** [comment]
For reference, this is how the coverage is generated:

COVERAGE=`which coverage`
echo "from gpkit.tests.test_repo import test_repo; test_repo(xmloutput=True)" > jenkins_test.py
python $COVERAGE run --append --source=. jenkins_test.py
python $COVERAGE html -d htmlcov --omit=gpkit/*,gpkit-models/*,venv2_gpkit/*,jenkins_test.py

So this should the directory htmlcov with coverage information for you to look at.

**Pull request merged**
