### PR TITLE
use default_solver instead of mutating installed_solvers

### PR DESCRIPTION
**Pull request by whoburg**
needed for #571.

Planning to merge if tests pass

### CODE REVIEW

**Comment by bqpd** [comment]
Won't you have to write "default_solver" to `env/settings` in build.py?

**Comment by whoburg** [comment]
nope, that's done in `__init__.py`.

**Comment by whoburg** [comment]
Turns out this is needed in #571 in order to reliably tell whether mosek is installed or not for one of the examples.

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
hmm, @galbramc unless I'm missing something it looks like the windows 7 machine is having some problems with remote file retrieval

**Comment by whoburg** [comment]
hmm, testing seems stalled.

**Comment by galbramc** [comment]
I upgraded to numpy-1.11.1. It takes a while the first time to do the
install. It won't take this long next time.

windows 7 had a strange connectivity failure again, but it worked on your
2nd try.

**Pull request merged**
