### PR TITLE
let's try not installing dependencies for pandas

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by galbramc** [comment]
strange, the build didn't trigger

test gpkit please

**Comment by galbramc** [comment]
test models please

**Comment by galbramc** [comment]
well it looks like conda create does not actually create a separate environment. pip install -e for both cvxopt and mosek appear to be installed int the base python, and hence creating a conflict. I guess I need to hunt more on the virtualenv numpy problem.

**Comment by bqpd** [comment]
:((( dangit

**Comment by galbramc** [comment]
we still probably want this fix to remove the uninstall of numpy

**Comment by bqpd** [comment]
Might it be better to instead update numpy on that computer to the newest version?

**Comment by galbramc** [comment]
No, using different versions of numpy on the different systems is part of the effort to test as many different versions of numpy as possible. Are you using --upgrade when you install pandas? Is so, that's the flag that needs to be removed to prevent pip from trying to upgrade the dependencies.

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@whoburg, merging to fix gpkit model tests on master

**Pull request merged**
