### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### hoburg/gpkit now has a Chat Room on Gitter

@bqpd has just created a chat room. You can visit it here: [https://gitter.im/gpkit-users/Lobby](https://gitter.im/gpkit-users/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/gpkit-users/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
verify this patch

**Comment by bqpd** [comment]
On second thought, not going to add this right away... but @whoburg, worth noting if we want to link to the chat from the readme

**Comment by whoburg** [comment]
sounds good, yeah let's add this if it ends up being a success.

**Pull request closed without merging**
