### PR TITLE
fix tests for pints 0.7

### LINKED ISSUE #544: newest version of pint breaks unit tests
upgrading pint causes unit tests to fail as discovered by @galbramc

### PR DESCRIPTION
**Pull request by bqpd**
Closes #544. @galbramc, I think this branch will pass tests with pints 0.7

### CODE REVIEW

**Comment by bqpd** [comment]
@galbramc, not sure why dependency tests didn't pass..they list no errors.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Pull request merged**
