### PR TITLE
no alternate sub syntax

### LINKED ISSUE #785: don't allow single subs to be comma-separated
it's two ways to do it :-/

### PR DESCRIPTION
**Pull request by bqpd**
closes #785

### CODE REVIEW

**Comment by whoburg** [comment]
looks great. I'll take a quick stab at the pylint errors

**Comment by whoburg** [comment]
retest this please (@galbramc I don't see how this caused pylint errors)

**Comment by whoburg** [comment]
I think the pylint stuff must have been fixed in another branch. I'm confused by the duplicate lines warning, which doesn't show up on my pylint checker. In any case, I'm going to try to reset the counts.

**Comment by whoburg** [comment]
@bqpd can I merge this when I'm ready?

**Comment by whoburg** [comment]
retest this please

**Comment by bqpd** [comment]
Yup, ready for merge as far as I'm concerned.

**Comment by galbramc** [comment]
These warnings looked legit, and you correctly suppressed them if you think the code is ok.

**Comment by whoburg** [comment]
agreed they're legit -- but I don't think they were introduced by this PR. There were some additional warnings, not introduced by this PR, on https://acdl.mit.edu/csi/job/gpkit_PullRequest_PyLint/577/; those went away when I reset the counts.

**Comment by galbramc** [comment]
Yeah, so this still harkens back to the issue that you have non-zero counts. If you can get the counts down to zero, you won't have issues with PR's introducing pylint warnings in each other.

**Pull request merged**
