### PR TITLE
remove stale patches and warnings

### PR DESCRIPTION
**Pull request by whoburg**
Removes an old pint patch (edit: actually, the patch is still needed)
Removes setup method warning
Removes out of date Modular ipynb

@bqpd, ready for review.

### CODE REVIEW

**Comment by whoburg** [comment]
hmph, looks like https://github.com/hgrecco/pint/issues/366 is not actually fixed on 0.7.2.

**Comment by bqpd** [comment]
So should we remove than unpatch?

**Comment by whoburg** [comment]
yeah I'll rebase and drop the unpatch.

**Comment by whoburg** [comment]
(force pushed)

**Comment by whoburg** [comment]
ready for re-review

**Pull request merged**
