### PR TITLE
added function

### PR DESCRIPTION
**Pull request by aechevarria1**
Put "monomials_strings" for function name, can change if needed.

### CODE REVIEW

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
you forgot the unit test to go with the function :)

**Comment by aechevarria1** [comment]
Does the unit test go in tests/t_tools.py? If not where would the unit test for this particular function go?

**Comment by galbramc** [comment]
Dunno, you have to ask @bqpd and @whoburg. I only help with jenkins, I don't actually work on gpkit.

**Comment by bqpd** [comment]
@aechevarria1 The test should go in `t_nomials` since this is a new function in `nomial_core`

**Comment by whoburg** [comment]
@aechevarria1 in case it's not obvious, you can push additional commits to this branch (`pylint-changes`) to create a unit test

**Comment by bqpd** [comment]
@galbramc, you did the same thing this commit was doing in the recent pylint clobber, right?

**Comment by galbramc** [comment]
Yes, @whoburg put the function in the small scripts scripts. Feel free to refactor to favor this version if you like it better.

**Comment by galbramc** [comment]
@whoburg  and @bqpd. Are you sure you didn't like this one better? This one comes with a unit test that we didn't add...

**Pull request closed without merging**
