### PR TITLE
test for 993

### PR DESCRIPTION
**Pull request by whoburg**
ready for review

### CODE REVIEW

**Comment by bqpd** [comment]
@whoburg, could you make a separate branch with the commit for #819, so I can merge that while we discuss #993?

**Comment by whoburg** [comment]
yep, on it

**Comment by bqpd** [comment]
(also, trying out not putting PRs in Release milestones, so they stay a bit more focused on Issues)

**Comment by whoburg** [comment]
roger.

**Comment by whoburg** [comment]
gonna rebase this and force push only the 993 commits

**Comment by whoburg** [comment]
closing, this tests something we don't want.

**Pull request closed without merging**
