### PR TITLE
initial prototype of interactive javascript charts, with @bqpd

### PR DESCRIPTION
**Pull request by whoburg**
In progress -- todo:

 - [ ] make it work with multiple datasets on the same plot, as in the chartjs examples
 - [ ] general cleanup of Python code for extensibility
 - [ ] figure out y axis scaling
 - [ ] add more chart options, e.g.
   - [ ] Radar? :imp: 
   - [ ] Pie
   - [ ] range/payload curves for aircraft
 - [ ] abstract to other js libraries

### CODE REVIEW

**Comment by whoburg** [comment]
Example to run in ipython notebook:

```python
from gpkit import Model, Variable
from gpkit.interactive.chartjs import BarChart

x = Variable("x", "-", "the variable called x")
y = Variable("y", "-", "the variable called y")
x_min = Variable("x_{min}", 2, "-", "min x val")
y_min = Variable("y_{min}", 2, "-", "min y val")

m = Model(x + y,
          [x >= x_min,
           y >= y_min])
sol = m.solve(verbosity=0)
bc = BarChart(["x", "y"])
```

screen shot 2016-02-24 at 7 53 43 pm

**Comment by whoburg** [comment]
@galbramc, this is now failing testing for a single pylint error, `Unable to import 'IPython.display'`. Is the right fix for you to install that on the testing machines?

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
Just wanted to make sure installing ipython fixed all the pylint warnings here, and it did.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by whoburg** [comment]
retest this please

**Comment by bqpd** [comment]
Not working on refactor right now.

**Comment by whoburg** [comment]
what's the status on this? Can I rebase it onto the current post-refactor master and force push?

**Comment by bqpd** [comment]
I think there was some bug, but once it's working I'm ready to pull.

**Comment by whoburg** [comment]
it was because we changed the items in `sol["variables"]` to be Quantities. rebased and fixed that. @bqpd, ready for review.

**Comment by bqpd** [comment]
Looks good to me, merging.

**Comment by bqpd** [comment]
Will make a new issue for the checklist above.

**Comment by whoburg** [comment]
@pgkirsch, check this out for the xplane sizing stuff. It's now on master. the small example code snippet above should work (and you'll need the controlpanel call shown in the screenshot in a separate cell).

**Pull request merged**
